# Gopkg.toml for github.com/ulule/amqpx

ignored = [
  "github.com/stretchr/testify/require"
]

[metadata]
  codename = "amqpx"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/streadway/amqp"
  revision = "e5adc2ada8b8efff032bf61173a233d143e9318e"
