version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    environment:
      AMQPX_CLUSTER_MODE: "true"
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init

      - run:
          name: Start docker container for RabbitMQ
          command: scripts/rabbitmq

      - run:
          name: Run tests
          command: scripts/go-wrapper test

      - run:
          name: Run linter
          command: scripts/go-wrapper lint
