#!/bin/bash

SOURCE_DIRECTORY=$(dirname "${BASH_SOURCE[0]}")
cd "${SOURCE_DIRECTORY}/.."

go get -d -u github.com/stretchr/testify/require

OPTIONS=""
if [ -n "$1" ]; then
    OPTIONS="$@"
fi

export AMQPX_CLUSTER_MODE="yes"

scripts/rabbitmq --start
sleep 10
go test -count=1 -v -race ${OPTIONS}
scripts/rabbitmq --stop
